name: New Release

on:
  push:
    branches: [ "master" ]

jobs:
  increment-version:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run version update script
        run: |
          cd REPOSaver
          ./incver_rel.ps1
        shell: pwsh

      - name: Create csproj artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: version-artifact
          path: REPOSaver/REPOSaver.csproj

      - name: Push updated version to master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add REPOSaver/REPOSaver.csproj
          git commit -m "Automated version increment"
          git push
        shell: pwsh

  update-dev:
    needs: increment-version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: dev

      - name: Merge Master to Dev
        run: |
          git pull origin master
          git push origin dev
        shell: pwsh
  
  build-and-publish:
    needs: increment-version
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 9.x

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore packages
        run: dotnet restore

      - name: Publish
        run: dotnet publish --no-restore -c Release

      - name: get_version
        run: |
          cd REPOSaver/
          [xml]$xml = Get-Content REPOSaver.csproj
          "version=$xml.Project.PropertyGroup.AssemblyVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Zip output
        run: |
          zip -d binaries.zip REPOSaver/bin/Release/net9.0-windows/publish/*

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
            artifacts: binaries.zip
            generateReleaseNotes: true
            name: "Version ${{ steps.get_version.outputs.version }}"
            commit: master
            tag: "v${{ steps.get_version.outputs.version }}"
      
          

